main:
    mode: test
    plt_show: True

    data_root: /home/sadid/PycharmProjects/mnist/files
    model_location: models

train:
    dataset: dataset/train.csv

    epochs: 1000
    steps_per_epoch: 100
    batch_size: 8